-- MySQL Script generated by MySQL Workbench
-- Sun Sep 29 14:54:46 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema infiori
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema infiori
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `infiori` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `infiori` ;


-- -----------------------------------------------------
-- Table `infiori`.`PRODUCTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infiori`.`PRODUCTS` (
  `id_products` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(200) NULL,
  `price` VARCHAR(45) NULL,
  `category` VARCHAR(45) NULL,
  `img_url` VARCHAR(255) NULL,
  `stock` VARCHAR(1) NULL,
   PRIMARY KEY (`id_products`))ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infiori`.`PICTURES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infiori`.`PICTURES` (
  `id_picture` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(45) NOT NULL,
   `id_producto` INT,
FOREIGN KEY (`id_producto`) REFERENCES `infiori`.`PRODUCTS`(`id_products`) ON DELETE CASCADE,
  PRIMARY KEY (`id_picture`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `infiori`.`USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infiori`.`USERS` (
  `id_user` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL,
  `firstname` VARCHAR(200) NULL,
  `mail` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `category` VARCHAR(45) NULL,
  `img_url` VARCHAR(255) NULL
  )ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `infiori`.`PIC_USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infiori`.`PIC_USER` (
  `id_picture` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(45) NOT NULL,
   `id_user` INT,
FOREIGN KEY (`id_user`) REFERENCES `USERS`(`id_user`) ON DELETE CASCADE,
  PRIMARY KEY (`id_picture`))
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `infiori`.`SHOPPING`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infiori`.`SHOPPING` (
  `id_shopping` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `date_info` DATE NOT NULL,
  `id_user` INT NOT NULL,
  `id_products` INT NOT NULL,
  CONSTRAINT `fk_SHOPPING_USERS` FOREIGN KEY (`id_user`) 
    REFERENCES `infiori`.`USERS` (`id_user`),
	CONSTRAINT `fk_SHOPPING_PRODUCTS` FOREIGN KEY (`id_products`) 
    REFERENCES `infiori`.`PRODUCTS` (`id_products`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



